### ISSUE TITLE
Add light map field to material.proto

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-msgs#109]
needed by ign-gazebo so we can convert the lightmap uri in SDF DOM to protobuf msgs and vice versa. 

This would be an ABI breaking change.

Related pull request: ignitionrobotics/ign-gazebo#471

**Comment by chapulina** [comment]
If #108 gets in and we end up deciding to use `ign-msgs7` on Edifice, we could get this in too.

**Comment by chapulina** [comment]
Edifice will use `ign-msgs7`. This was addressed on #111.
