### ISSUE TITLE
Documentation for generated C++

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-msgs#12]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/issues/12)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See [this](https://bitbucket.org/osrf/gazebo/issues/2153/message-api-documentation-broken) gazebo issue

And [this](http://answers.gazebosim.org/question/16295/where-i-can-find-contact_size-function/) question

**Comment by ahcorde** [comment]
I create a new argument called `AUTOGENERATED_DOC` in ign-cmake to be be able to include the directory where the autogenerated code is saved. https://github.com/ignitionrobotics/ign-cmake/pull/108

This other PR makes use of this new feature

**Comment by chapulina** [comment]
Done on #76. See #77 for actually documenting that API.
