### ISSUE TITLE
Is it ok to install both ign-msgs5 and ign-msgs7?

### ISSUE THREAD

**Issue by kevinsmia1939** [ignitionrobotics/ign-msgs#156]
Hi,

I am trying to build Gazebo 11 on openSUSE Linux.

Ignition-transport8 need Ignition-msgs version 5.
Ignition-fuel-tools6 need Ignition-msgs version 7.

Would it be ok to use 2 version of ign-msgs like this or do I have to down-grade Ignition-fuel-tools to make it use Ignition-msgs version 5?

Thanks.

**Comment by traversaro** [comment]
Hi @kevinsmia1939, I think that Gazebo11 requires `ignition-fuel-tools4`, see:
* https://github.com/osrf/gazebo/blob/gazebo11/cmake/SearchForStuff.cmake#L793
* https://github.com/ignition-tooling/gazebodistro/blob/master/gazebo11.yaml#L17

**Comment by kevinsmia1939** [comment]
Thanks for the help.
