### ISSUE TITLE
CmdLine.Msg* test failures on homebrew

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-msgs#20]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/issues/20)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The [CmdLine.MsgList](https://build.osrfoundation.org/job/ignition_msgs-ci-ign-msgs1-homebrew-amd64/7/testReport/(root)/CmdLine/MsgList/) and [CmdLine.MsgInfo](https://build.osrfoundation.org/job/ignition_msgs-ci-ign-msgs1-homebrew-amd64/7/testReport/(root)/CmdLine/MsgInfo/) tests ~~used to pass but are failing since~~ were added in [pull request #56](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/pull-requests/56) but fail on homebrew.

**Comment by scpeters** [comment]
this is working now

* https://build.osrfoundation.org/job/ignition_msgs-ci-ign-msgs6-homebrew-amd64/3/testReport/(root)/CmdLine/
