### ISSUE TITLE
Optional fields in proto 3

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-msgs#22]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/issues/22)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
On Protobuf 3 all fields are optional, but only nested messages have the `has_msg` API (i.e. leaf fields don't have a `has_field`). Protobuf will also automatically set default values to fields which are unset, such as 0 to int and false to booleans.

This means that it is impossible to know if a boolean was set to false or if it is unset.

For example, the `WorldStatistics` message has the following fields:

~~~
bool paused
int32 model_count
~~~

When receiving a message with paused false and zero models, we don't know if that's indeed true.

This could be just something to be aware from the publishing side (i.e. make sure to always set leaf fields), or maybe we want to restructure the messages to avoid this.

One suggestion would be to change leaf fields for nested messages, for example:

~~~
Boolean paused
Int32 model_count
~~~

**Comment by nkoenig** [comment]
I'm going to close this issue since there is a work around for optional field, when required. See the [PID message](https://github.com/ignitionrobotics/ign-msgs/blob/ign-msgs6/proto/ignition/msgs/pid.proto) as an example.
