### ISSUE TITLE
[Citadel] Update JointCmd and PID messages to support optional fields

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-msgs#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/issues/35)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
In `gazebo::msgs` and ign-msgs2 and earlier, we used `proto2` syntax, in which it could be determined which fields were unset. Since `ign-msgs3`, we are using `proto3` syntax, in which unset fields of primitive leaf types (string, int, float, etc) are indistinguishable from fields with a default value. This is problematic for the JointController in `osrf/gazebo`, in which position PID, velocity PID, and force control can be applied additively in any combination. It is common to use a PID control along with a feed-forward force parameter to counteract constant disturbances (like gravity compensation).

Currently this is problematic for the `JointCmd` and `PID` messages because `JointCMD::force` is a double, and the `target` and gain values in `PID` are `double`. So it will work if you are only sending a `force`, but if you simply want to update the `target` of a PID controller, that will reset the `force` and the PID gains unless you repeat those values.

cc @chapulina  @iche033  @azeey

Let's think about doing this before the `ign-msgs5` cutoff.

**Comment by chapulina** [comment]
I believe this was addressed on this PR: https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/pull-requests/162/page/1
