### ISSUE TITLE
Expose message generation framework

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-msgs#36]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-msgs/issues/36)) by Anonymous.**

----------------------------------------
# Summary

I'm trying to add custom messages to my ignition project. Since `ign-msgs` doesn't seem to expose this functionality, I had to copy the cmake macro `ign_msgs_protoc` from `ign-msgs/src/CMakeLists.txt` into my own project, along with the generator source files: `ign-msgs/src/Generator.cc`, `ign-msgs/src/Generator.hh`, `ign-msgs/src/generator_main.cc`. Although this works, it's not a clean solution. Are there any plans to export the message generation framework so it can be used by other projects?

**Comment by mjcarroll** [comment]
This was completed in #339, tutorial added in: https://github.com/gazebosim/gz-msgs/pull/386
